# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/kvstore/kvstore.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/kvstore/kvstore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/kvstore/kvstore.proto\x12\x07kvstore\"=\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x13\n\x0bttl_seconds\x18\x03 \x01(\x05\"\r\n\x0bPutResponse\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x10\n\x0e\x44\x65leteResponse\"\x1d\n\x0bListRequest\x12\x0e\n\x06prefix\x18\x01 \x01(\t\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"0\n\x0cListResponse\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.kvstore.KeyValue2\xe3\x01\n\rKeyValueStore\x12\x30\n\x03Put\x12\x13.kvstore.PutRequest\x1a\x14.kvstore.PutResponse\x12\x30\n\x03Get\x12\x13.kvstore.GetRequest\x1a\x14.kvstore.GetResponse\x12\x39\n\x06\x44\x65lete\x12\x16.kvstore.DeleteRequest\x1a\x17.kvstore.DeleteResponse\x12\x33\n\x04List\x12\x14.kvstore.ListRequest\x1a\x15.kvstore.ListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.kvstore.kvstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUTREQUEST']._serialized_start=41
  _globals['_PUTREQUEST']._serialized_end=102
  _globals['_PUTRESPONSE']._serialized_start=104
  _globals['_PUTRESPONSE']._serialized_end=117
  _globals['_GETREQUEST']._serialized_start=119
  _globals['_GETREQUEST']._serialized_end=144
  _globals['_GETRESPONSE']._serialized_start=146
  _globals['_GETRESPONSE']._serialized_end=174
  _globals['_DELETEREQUEST']._serialized_start=176
  _globals['_DELETEREQUEST']._serialized_end=204
  _globals['_DELETERESPONSE']._serialized_start=206
  _globals['_DELETERESPONSE']._serialized_end=222
  _globals['_LISTREQUEST']._serialized_start=224
  _globals['_LISTREQUEST']._serialized_end=253
  _globals['_KEYVALUE']._serialized_start=255
  _globals['_KEYVALUE']._serialized_end=293
  _globals['_LISTRESPONSE']._serialized_start=295
  _globals['_LISTRESPONSE']._serialized_end=343
  _globals['_KEYVALUESTORE']._serialized_start=346
  _globals['_KEYVALUESTORE']._serialized_end=573
# @@protoc_insertion_point(module_scope)
